// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEmKBhZUmfzTwr9dk4qxQUW_hwU_0MJ0A',
    appId: '1:927960766101:web:9390385c430ae13ac16d9c',
    messagingSenderId: '927960766101',
    projectId: 'it-scans-d9671',
    authDomain: 'it-scans-d9671.firebaseapp.com',
    storageBucket: 'it-scans-d9671.firebasestorage.app',
    measurementId: 'G-QGGED9MQX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1R-CeMscdHfCIs4GHlF_urtRkG3f2D0E',
    appId: '1:927960766101:android:f930dc46b91c6314c16d9c',
    messagingSenderId: '927960766101',
    projectId: 'it-scans-d9671',
    storageBucket: 'it-scans-d9671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy_hlxIKuz0hsk2FSeVSBmpuCbjSxsMwE',
    appId: '1:927960766101:ios:08a54cfeb2a15f56c16d9c',
    messagingSenderId: '927960766101',
    projectId: 'it-scans-d9671',
    storageBucket: 'it-scans-d9671.firebasestorage.app',
    iosBundleId: 'com.syeds.itscans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy_hlxIKuz0hsk2FSeVSBmpuCbjSxsMwE',
    appId: '1:927960766101:ios:9c42291d8461ea54c16d9c',
    messagingSenderId: '927960766101',
    projectId: 'it-scans-d9671',
    storageBucket: 'it-scans-d9671.firebasestorage.app',
    iosBundleId: 'com.example.docuscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEmKBhZUmfzTwr9dk4qxQUW_hwU_0MJ0A',
    appId: '1:927960766101:web:33aeae7a2e1c7db2c16d9c',
    messagingSenderId: '927960766101',
    projectId: 'it-scans-d9671',
    authDomain: 'it-scans-d9671.firebaseapp.com',
    storageBucket: 'it-scans-d9671.firebasestorage.app',
    measurementId: 'G-YPY5W46KTC',
  );
}
