default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    # upload_to_play_store(track: 'beta') # Uncomment when keys are ready
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    # upload_to_play_store # Uncomment when keys are ready
  end
end
